#!/bin/bash
echo "# Rocket Issue #2377" > test3.md

echo -e 'This file is generated by `test3.sh`' >> test3.md
echo -e 'Full logs can be found in [test3-troubleshooting.md](https://github.com/danielclough/Rocket-2377/blob/main/test3-troubleshooting.md) and [test3-dumpcap.test](https://github.com/danielclough/Rocket-2377/blob/main/test3-dumpcap.test).' >> test3.md

echo -e "\n## Try file-lg.txt (954715) with python (unexpected fail)\n" >> test3.md
echo '```' >> test3.md
python3 post_lg.py >> test3.md
echo '```' >> test3.md

echo -e "\n\n## Try file-lg.txt (954715) with curl (expected fail)\n" >> test3.md
echo '```' >> test3.md
curl -v \
 -F file=@file-lg.txt -F name=file-lg.txt \
 http://127.0.0.1:8000/upload  >> test3.md
echo -e '\n```' >> test3.md


echo -e "\n## Try file-sm.txt (954715) with python (unexpected fail)\n" >> test3.md
echo '```' >> test3.md
python3 post_sm.py >> test3.md
echo '```' >> test3.md

echo -e "\n\n## Try file-sm.txt (954715) with curl (expected fail)\n" >> test3.md
echo '```' >> test3.md
curl -v \
 -F file=@file-sm.txt -F name=file-sm.txt \
 http://127.0.0.1:8000/upload  >> test3.md
echo -e '\n```' >> test3.md


echo -e "\n## Try file-xs.txt (954715) with python (unexpected pass)\n" >> test3.md
echo '```' >> test3.md
python3 post_xs.py >> test3.md
echo '```' >> test3.md

echo -e "\n\n## Try file-xs.txt (954715) with curl (expected pass)\n" >> test3.md
echo '```' >> test3.md
curl -v \
 -F file=@file-xs.txt -F name=file-xs.txt \
 http://127.0.0.1:8000/upload  >> test3.md
echo -e '\n```' >> test3.md

