#!/bin/bash
echo "# Rocket Issue #2377" > README.md

echo 'This file is generated by `test.sh` to demonstrate inconsistent filesize requirements which may be the cause of this issue. Full logs can be found in `troubleshooting.md`.' >> README.md

echo -e "\n## 3 filesizes\n" >> README.md
echo '```' >> README.md
ls -al file-lg.txt file-sm.txt file-xs.txt >> README.md
echo '```' >> README.md

echo -e "\n## Try small file with python\n" >> README.md
echo '```' >> README.md
python3 post_sm.py >> README.md
echo '```' >> README.md

echo -e "\n## Try large file with python\n" >> README.md
echo '```' >> README.md
python3 post_lg.py 2>> README.md
echo '```' >> README.md

echo -e "\n## Try with small file with curl\n" >> README.md
echo '```' >> README.md
curl -v \
 -F file=@file-sm.txt -F name=file-sm.txt \
 http://127.0.0.1:8000/upload  >> README.md
echo -e '\n```' >> README.md

echo -e "\n\n## Try x-small file with curl\n" >> README.md
echo '```' >> README.md
curl -v \
 -F file=@file-xs.txt -F name=file-xs.txt \
 http://127.0.0.1:8000/upload  >> README.md
echo -e '\n```' >> README.md