#!/bin/bash
echo "# Rocket Issue #2377" > README.md

echo -e 'This file is generated by `test.sh` to demonstrate unintuitive filesize requirements for `curl` vs `python requests`. Perhaps related [Built-in Limits](https://api.rocket.rs/v0.5-rc/rocket/data/struct.Limits.html#built-in-limits).\n\nIt seems that the type `TempFile` should always involve a 1MB limit, but it can accept 2MB from `python requsts`.\n\nThe greatest problem for reconciling my results with the OP is that `curl` accepts a smaller filesize, and OP had it working with `curl` but not `python requests`.\n\n' >> README.md
echo -e 'Full logs can be found in [troubleshooting.md](https://github.com/danielclough/Rocket-2377/blob/main/troubleshooting.md).' >> README.md

echo -e "\n## 3 filesizes\n" >> README.md
echo '```' >> README.md
ls -al file-lg.txt file-sm.txt file-xs.txt >> README.md
echo '```' >> README.md

echo -e "\n## Try file-lg.txt (2097506) with python (expected fail)\n" >> README.md
echo '```' >> README.md
python3 post_lg.py 2>> README.md
echo '```' >> README.md

echo -e "\n## Try file-sm.txt (2096373) with python (unexpected pass)\n" >> README.md
echo '```' >> README.md
python3 post_sm.py >> README.md
echo '```' >> README.md

echo -e "\n## Try file-sm.txt (2096373) with curl (expected fail)\n" >> README.md
echo '```' >> README.md
curl -v \
 -F file=@file-sm.txt -F name=file-sm.txt \
 http://127.0.0.1:8000/upload  >> README.md
echo -e '\n```' >> README.md

echo -e "\n\n## Try file-xs.txt (954715) with curl (expected pass)\n" >> README.md
echo '```' >> README.md
curl -v \
 -F file=@file-xs.txt -F name=file-xs.txt \
 http://127.0.0.1:8000/upload  >> README.md
echo -e '\n```' >> README.md